-- 补齐 6 张"实体有、迁移从未建过"的表。此前 e2e 老库里这些表由历史 ddl-auto=update
-- 时代残留，掩盖了漂移；干净库上 Flyway 建不出它们，ddl-auto=validate 拒绝启动。
-- DDL 与实体定义一一对应（导出工具：test/.../tools/SchemaDiffExportTest）。

-- AnnouncementEntity → announcements
CREATE TABLE announcements (
    id varchar(32) NOT NULL,
    game_id varchar(32) NOT NULL,
    environment_id varchar(64),
    title varchar(200) NOT NULL,
    content TEXT NOT NULL,
    channel varchar(20) NOT NULL CHECK (channel IN ('LOBBY','MARQUEE','PUSH','ALL')),
    status varchar(20) NOT NULL CHECK (status IN ('DRAFT','SCHEDULED','PUBLISHED','OFFLINE')),
    priority integer NOT NULL,
    created_by varchar(64),
    scheduled_at timestamp(6),
    published_at timestamp(6),
    offline_at timestamp(6),
    auto_offline_at timestamp(6),
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6) NOT NULL,
    deleted_at timestamp(6),
    PRIMARY KEY (id)
);

-- ExperimentMetricSnapshotEntity → experiment_metric_snapshots
CREATE TABLE experiment_metric_snapshots (
    id varchar(64) NOT NULL,
    experiment_id varchar(64) NOT NULL,
    metric_name varchar(100) NOT NULL,
    variant varchar(100) NOT NULL,
    window_start bigint NOT NULL,
    count bigint NOT NULL,
    sum double precision NOT NULL,
    sum_squares double precision NOT NULL,
    successes bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    PRIMARY KEY (id)
);

-- FunnelConfigEntity → funnel_configs（ConfigurableFunnelsJob 的旧配置表；
-- 当前 job 已改读 funnel_analyses/funnel_steps，表按实体补齐保留）
CREATE TABLE funnel_configs (
    id varchar(32) NOT NULL,
    game_id varchar(32) NOT NULL,
    user_key varchar(50) NOT NULL,
    name varchar(100) NOT NULL,
    description varchar(500),
    type varchar(255) NOT NULL CHECK (type IN ('STANDARD','SEQUENTIAL','TIME_WINDOW','UNORDERED')),
    time_window_sec bigint,
    enabled boolean,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6) NOT NULL,
    deleted_at timestamp(6),
    PRIMARY KEY (id)
);

-- MailEntity → op_mails（运营邮件）
CREATE TABLE op_mails (
    id varchar(32) NOT NULL,
    game_id varchar(32) NOT NULL,
    environment_id varchar(64),
    title varchar(200) NOT NULL,
    content TEXT NOT NULL,
    attachments TEXT,
    recipients varchar(4000),
    scope varchar(20) NOT NULL CHECK (scope IN ('ALL','INDIVIDUAL')),
    status varchar(20) NOT NULL CHECK (status IN ('DRAFT','SENT','EXPIRED')),
    created_by varchar(64),
    expire_at timestamp(6),
    sent_at timestamp(6),
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6) NOT NULL,
    deleted_at timestamp(6),
    PRIMARY KEY (id)
);

-- MailClaimEntity → op_mail_claims（玩家领取记录，一人一邮件一条）
CREATE TABLE op_mail_claims (
    id varchar(48) NOT NULL,
    mail_id varchar(32) NOT NULL,
    player_key varchar(128) NOT NULL,
    game_id varchar(32) NOT NULL,
    claimed_attachments TEXT,
    claimed_at timestamp(6) NOT NULL,
    created_at timestamp(6) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_claim_mail_player UNIQUE (mail_id, player_key)
);

-- UserRoleEntity → user_role_assignments（环境级角色授权）
CREATE TABLE user_role_assignments (
    id bigint generated by default as identity,
    user_id varchar(64) NOT NULL,
    role_id varchar(50) NOT NULL,
    game_id varchar(32),
    environment varchar(20),
    enabled boolean,
    assigned_by varchar(64),
    assigned_at timestamp(6) NOT NULL,
    expires_at timestamp(6),
    PRIMARY KEY (id)
);

-- ————— 以下补"实体有列、迁移从未建过"的缺失列（同根因：老库残留掩盖）—————

-- AuditLogEntity：审计明细 10 列
ALTER TABLE audit_logs ADD COLUMN details text;
ALTER TABLE audit_logs ADD COLUMN old_value text;
ALTER TABLE audit_logs ADD COLUMN new_value text;
ALTER TABLE audit_logs ADD COLUMN username varchar(100);
ALTER TABLE audit_logs ADD COLUMN status varchar(255);
ALTER TABLE audit_logs ADD COLUMN session_id varchar(100);
ALTER TABLE audit_logs ADD COLUMN ip_address varchar(45);
ALTER TABLE audit_logs ADD COLUMN duration_ms bigint;
ALTER TABLE audit_logs ADD COLUMN game_id varchar(32);
ALTER TABLE audit_logs ADD COLUMN environment varchar(20);

-- EventPropertyDefinitionEntity：基数上限
ALTER TABLE event_property_definitions ADD COLUMN cardinality_limit integer;

-- FunnelStepEntity：展示与窗口 6 列（e2e verify 第 15 节的 INSERT 依赖 funnel_id/name）
ALTER TABLE funnel_steps ADD COLUMN funnel_id varchar(32);
ALTER TABLE funnel_steps ADD COLUMN name varchar(100);
ALTER TABLE funnel_steps ADD COLUMN color varchar(20);
ALTER TABLE funnel_steps ADD COLUMN icon varchar(50);
ALTER TABLE funnel_steps ADD COLUMN optional boolean;
ALTER TABLE funnel_steps ADD COLUMN time_window_sec bigint;

-- GameEntity：默认时区
ALTER TABLE games ADD COLUMN default_timezone varchar(64);

-- PermissionEntity：启用/资源类型/系统内置
ALTER TABLE permissions ADD COLUMN enabled boolean;
ALTER TABLE permissions ADD COLUMN resource_type varchar(50);
ALTER TABLE permissions ADD COLUMN system boolean;

-- RoleEntity：启用/系统内置
ALTER TABLE roles ADD COLUMN enabled boolean;
ALTER TABLE roles ADD COLUMN system boolean;
