-- 补齐 6 张"实体有、迁移从未建过"的表。此前 e2e 老库里这些表由历史 ddl-auto=update
-- 时代残留，掩盖了漂移；干净库上 Flyway 建不出它们，ddl-auto=validate 拒绝启动。
-- DDL 与实体定义一一对应（导出工具：test/.../tools/SchemaDiffExportTest）。
-- 全语句 IF NOT EXISTS 幂等：同批残留表/列在老库（e2e）上会撞 "already exists"，
-- 干净库上则全量执行；两种终态 schema 一致，漂移由启动时 validate 兜底。

-- AnnouncementEntity → announcements
CREATE TABLE IF NOT EXISTS announcements (
    id varchar(32) NOT NULL,
    game_id varchar(32) NOT NULL,
    environment_id varchar(64),
    title varchar(200) NOT NULL,
    content TEXT NOT NULL,
    channel varchar(20) NOT NULL CHECK (channel IN ('LOBBY','MARQUEE','PUSH','ALL')),
    status varchar(20) NOT NULL CHECK (status IN ('DRAFT','SCHEDULED','PUBLISHED','OFFLINE')),
    priority integer NOT NULL,
    created_by varchar(64),
    scheduled_at timestamp(6),
    published_at timestamp(6),
    offline_at timestamp(6),
    auto_offline_at timestamp(6),
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6) NOT NULL,
    deleted_at timestamp(6),
    PRIMARY KEY (id)
);

-- ExperimentMetricSnapshotEntity → experiment_metric_snapshots
CREATE TABLE IF NOT EXISTS experiment_metric_snapshots (
    id varchar(64) NOT NULL,
    experiment_id varchar(64) NOT NULL,
    metric_name varchar(100) NOT NULL,
    variant varchar(100) NOT NULL,
    window_start bigint NOT NULL,
    count bigint NOT NULL,
    sum double precision NOT NULL,
    sum_squares double precision NOT NULL,
    successes bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    PRIMARY KEY (id)
);

-- FunnelConfigEntity → funnel_configs（ConfigurableFunnelsJob 的旧配置表；
-- 当前 job 已改读 funnel_analyses/funnel_steps，表按实体补齐保留）
CREATE TABLE IF NOT EXISTS funnel_configs (
    id varchar(32) NOT NULL,
    game_id varchar(32) NOT NULL,
    user_key varchar(50) NOT NULL,
    name varchar(100) NOT NULL,
    description varchar(500),
    type varchar(255) NOT NULL CHECK (type IN ('STANDARD','SEQUENTIAL','TIME_WINDOW','UNORDERED')),
    time_window_sec bigint,
    enabled boolean,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6) NOT NULL,
    deleted_at timestamp(6),
    PRIMARY KEY (id)
);

-- MailEntity → op_mails（运营邮件）
CREATE TABLE IF NOT EXISTS op_mails (
    id varchar(32) NOT NULL,
    game_id varchar(32) NOT NULL,
    environment_id varchar(64),
    title varchar(200) NOT NULL,
    content TEXT NOT NULL,
    attachments TEXT,
    recipients varchar(4000),
    scope varchar(20) NOT NULL CHECK (scope IN ('ALL','INDIVIDUAL')),
    status varchar(20) NOT NULL CHECK (status IN ('DRAFT','SENT','EXPIRED')),
    created_by varchar(64),
    expire_at timestamp(6),
    sent_at timestamp(6),
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6) NOT NULL,
    deleted_at timestamp(6),
    PRIMARY KEY (id)
);

-- MailClaimEntity → op_mail_claims（玩家领取记录，一人一邮件一条）
CREATE TABLE IF NOT EXISTS op_mail_claims (
    id varchar(48) NOT NULL,
    mail_id varchar(32) NOT NULL,
    player_key varchar(128) NOT NULL,
    game_id varchar(32) NOT NULL,
    claimed_attachments TEXT,
    claimed_at timestamp(6) NOT NULL,
    created_at timestamp(6) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_claim_mail_player UNIQUE (mail_id, player_key)
);

-- UserRoleEntity → user_role_assignments（环境级角色授权）
CREATE TABLE IF NOT EXISTS user_role_assignments (
    id bigint generated by default as identity,
    user_id varchar(64) NOT NULL,
    role_id varchar(50) NOT NULL,
    game_id varchar(32),
    environment varchar(20),
    enabled boolean,
    assigned_by varchar(64),
    assigned_at timestamp(6) NOT NULL,
    expires_at timestamp(6),
    PRIMARY KEY (id)
);

-- ————— 以下补"实体有列、迁移从未建过"的缺失列（同根因：老库残留掩盖）—————

-- AuditLogEntity：审计明细 10 列
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS details text;
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS old_value text;
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS new_value text;
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS username varchar(100);
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS status varchar(255);
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS session_id varchar(100);
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS ip_address varchar(45);
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS duration_ms bigint;
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS game_id varchar(32);
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS environment varchar(20);

-- EventPropertyDefinitionEntity：基数上限
ALTER TABLE event_property_definitions ADD COLUMN IF NOT EXISTS cardinality_limit integer;

-- FunnelStepEntity：展示与窗口 6 列（e2e verify 第 15 节的 INSERT 依赖 funnel_id/name）
ALTER TABLE funnel_steps ADD COLUMN IF NOT EXISTS funnel_id varchar(32);
ALTER TABLE funnel_steps ADD COLUMN IF NOT EXISTS name varchar(100);
ALTER TABLE funnel_steps ADD COLUMN IF NOT EXISTS color varchar(20);
ALTER TABLE funnel_steps ADD COLUMN IF NOT EXISTS icon varchar(50);
ALTER TABLE funnel_steps ADD COLUMN IF NOT EXISTS optional boolean;
ALTER TABLE funnel_steps ADD COLUMN IF NOT EXISTS time_window_sec bigint;

-- GameEntity：默认时区
ALTER TABLE games ADD COLUMN IF NOT EXISTS default_timezone varchar(64);

-- PermissionEntity：启用/资源类型/系统内置
ALTER TABLE permissions ADD COLUMN IF NOT EXISTS enabled boolean;
ALTER TABLE permissions ADD COLUMN IF NOT EXISTS resource_type varchar(50);
ALTER TABLE permissions ADD COLUMN IF NOT EXISTS system boolean;

-- RoleEntity：启用/系统内置
ALTER TABLE roles ADD COLUMN IF NOT EXISTS enabled boolean;
ALTER TABLE roles ADD COLUMN IF NOT EXISTS system boolean;

-- ————— 老库残留类型收敛：float8 → numeric —————
-- 这 11 列由历史 ddl-auto=update 建为 double precision；实体已统一 @JdbcTypeCode(NUMERIC)
-- （与迁移建表 DDL 一致），validate 按 typecode 比对，float8 直接拒绝启动。
-- ALTER TYPE 对已是 numeric 的列为 no-op，干净库/老库均幂等。
ALTER TABLE event_fields ALTER COLUMN min_value TYPE numeric USING min_value::numeric;
ALTER TABLE event_fields ALTER COLUMN max_value TYPE numeric USING max_value::numeric;
ALTER TABLE event_property_definitions ALTER COLUMN min_value TYPE numeric USING min_value::numeric;
ALTER TABLE event_property_definitions ALTER COLUMN max_value TYPE numeric USING max_value::numeric;
ALTER TABLE game_environments ALTER COLUMN sample_rate TYPE numeric USING sample_rate::numeric;
ALTER TABLE game_environments ALTER COLUMN error_threshold TYPE numeric USING error_threshold::numeric;
ALTER TABLE games ALTER COLUMN sample_rate TYPE numeric USING sample_rate::numeric;
ALTER TABLE identities ALTER COLUMN confidence_score TYPE numeric USING confidence_score::numeric;
ALTER TABLE identity_links ALTER COLUMN link_strength TYPE numeric USING link_strength::numeric;
ALTER TABLE level_progressions ALTER COLUMN anomaly_threshold TYPE numeric USING anomaly_threshold::numeric;
ALTER TABLE retention_analyses ALTER COLUMN confidence_level TYPE numeric USING confidence_level::numeric;
